## PULL IMAGE
FROM NODE:18.16.0

## DIR KERJA
WORKDIR /apps

##  COPY FILE DARI HOST LINUX KE WORKDIR CONTAINER
ADD apps/. /apps

## INSTALL MODULE PADA SAAT PEMBUATAN IMAGE
RUN npm INSTALL

## MENJALANKAN PERINTAH PADA SAAT CONTAINER JALAN
CMD npm start

## EXPOSE PORT
EXPOSE 3000 